# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  - main
  - release/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'target/classes'
    codeCoverageSourceDirectories: 'src/main/java'
    goals: 'package'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(6e8cc58a-23e7-480d-87d2-eda8ae44abb8)'
    appType: 'webAppLinux'
    appName: 'furst-spring'
    package: '$(System.DefaultWorkingDirectory)/**/target/*.jar'
    runtimeStack: 'JAVA|17-java17'